import { rankVoteDates } from '../model/ranking'
import type { DateVoteStatus } from '../model/types'
import { formatDate } from '../../../shared/utils/format'
import { panelClass } from '../../../shared/ui/styles'

export function VoteStatusPanel({ voteStatus, participantsCount, loading }: { voteStatus: DateVoteStatus[]; participantsCount: number; loading: boolean }) {
  const ranked = rankVoteDates(voteStatus)
  if (loading) return <section className={`${panelClass} grid min-h-[250px] place-content-center text-[#69809f]`}>투표 현황을 불러오는 중이에요.</section>
  return <section className={`${panelClass} p-[25px] max-[800px]:p-5`}><div className="mb-5"><div><h2 className="m-0 text-[21px] font-black tracking-[-0.04em] text-[#19365e]">투표 현황</h2><p className="mt-1.5 mb-0 text-xs text-[#7b8da8]">가능 응답이 많은 순서로 날짜를 추천해요.</p></div></div>{ranked.length === 0 ? <div className="grid min-h-[250px] place-content-center text-[#69809f]">아직 표시할 날짜가 없어요.</div> : <div className="grid gap-2.5">{ranked.map(({ item, available, maybe, unavailable }, index) => <article className="flex items-center gap-3 rounded-[11px] border border-[#e4ebf4] p-3 max-[520px]:flex-wrap max-[520px]:items-start" key={item.date_option_id}><span className="grid size-[29px] shrink-0 place-items-center rounded-full bg-[#e9f3ff] text-xs font-black text-brand-500">{index + 1}</span><div><h3 className="m-0 text-sm font-black text-[#284568]">{formatDate(item.date_value)}</h3><p className="mt-1 mb-0 text-xs text-[#8191a9]">아직 응답하지 않음 {Math.max(0, participantsCount - item.votes.length)}명</p></div><div className="ml-auto flex flex-wrap justify-end gap-[5px] max-[520px]:ml-[41px] max-[520px]:w-full max-[520px]:justify-start"><span className="rounded-full bg-[#e2f8eb] px-2 py-[5px] text-xs font-extrabold text-[#168a57]">가능 {available}</span><span className="rounded-full bg-[#fff5d8] px-2 py-[5px] text-xs font-extrabold text-[#a97300]">애매 {maybe}</span><span className="rounded-full bg-[#ffebeb] px-2 py-[5px] text-xs font-extrabold text-[#dc6060]">불가 {unavailable}</span></div></article>)}</div>}</section>
}
