date-format %d/%b/%Y
time-format %H:%M:%S
log-format %h %^[%d:%t %^] "%m %U %H" %s %b "%u" %T

tz Asia/Seoul
no-query-string true
anonymize-ip true
anonymize-level 1
unknowns-as-crawlers true
no-progress true
html-report-title moim 접속 현황
